"""Serializable domain objects and validated world configuration."""

import copy
import json
from dataclasses import asdict, dataclass
from importlib import resources
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


@dataclass(frozen=True)
class BeliefState:
    """Facts the actor has learned; this is not the complete world truth."""

    known_facts: List[str]


@dataclass(frozen=True)
class Memory:
    """An actor-visible recollection with its source event."""

    id: str
    event_id: str
    tick: int
    summary: str
    actor_ids: List[str]
    location: str
    importance: int


@dataclass(frozen=True)
class NPC:
    """A game entity with private knowledge and explicit action permissions."""

    id: str
    name: str
    role: str
    persona: str
    goal: str
    location: str
    inventory: List[str]
    trust: Dict[str, int]
    belief: BeliefState
    allowed_actions: List[str]
    memories: List[Memory]


@dataclass(frozen=True)
class Observation:
    """Only the actors and objects currently visible to one actor."""

    location: str
    visible_actors: List[Dict[str, Any]]
    visible_items: List[Dict[str, Any]]
    available_locations: List[Dict[str, Any]]
    recent_events: List[Dict[str, Any]]


@dataclass(frozen=True)
class Action:
    """A parsed intent. Free-form speech is deliberately not an action."""

    type: str
    actor_id: str
    target_id: Optional[str] = None
    topic: Optional[str] = None
    location_id: Optional[str] = None
    item_id: Optional[str] = None

    def to_dict(self) -> Dict[str, str]:
        """Return just the fields belonging to this action type."""
        return {key: value for key, value in asdict(self).items() if value is not None}


@dataclass(frozen=True)
class Event:
    """An append-only fact generated by a committed action."""

    id: str
    tick: int
    type: str
    actor_id: str
    location: str
    participants: List[str]
    witnesses: List[str]
    summary: str
    action: Dict[str, str]


@dataclass(frozen=True)
class Trace:
    """An immutable-by-copy envelope for a complete decision record."""

    data: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        """Return an independent, JSON-serializable decision record."""
        return copy.deepcopy(self.data)


class WorldState:
    """World truth exposed as copies; only the executor commits changes."""

    def __init__(self, data: Dict[str, Any]):
        validate_world(data)
        self._data = copy.deepcopy(data)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "WorldState":
        """Validate and detach a world snapshot."""
        return cls(data)

    @property
    def tick(self) -> int:
        """Logical time of the last committed world event."""
        return self._data["tick"]

    @property
    def actors(self) -> Dict[str, NPC]:
        """Return detached typed actor snapshots."""
        result = {}
        for key, value in self._data["actors"].items():
            actor = copy.deepcopy(value)
            actor["belief"] = BeliefState(**actor["belief"])
            actor["memories"] = [Memory(**memory) for memory in actor["memories"]]
            result[key] = NPC(**actor)
        return result

    def to_dict(self) -> Dict[str, Any]:
        """Return a full debugger snapshot, including hidden world facts."""
        return copy.deepcopy(self._data)

    def _commit(self, data: Dict[str, Any]) -> None:
        validate_world(data)
        self._data = copy.deepcopy(data)


def validate_world(data: Any) -> None:
    """Reject malformed configuration before any world is created."""
    if not isinstance(data, dict):
        raise ValueError("World must be a JSON object")
    required = {"id", "name", "tick", "locations", "actors", "items", "facts", "quests", "events"}
    if not required <= set(data) <= required | {"rules"}:
        raise ValueError("World fields must include " + ", ".join(sorted(required)) + "; only rules is optional")
    if type(data["tick"]) is not int or data["tick"] < 0:
        raise ValueError("World tick must be a non-negative integer")
    for field in ("id", "name"):
        if not isinstance(data[field], str) or not data[field]:
            raise ValueError("World " + field + " must be a non-empty string")
    for field in ("locations", "actors", "items", "facts", "quests"):
        if not isinstance(data[field], dict):
            raise ValueError("World " + field + " must be an object")
        if any(not isinstance(key, str) or not key for key in data[field]):
            raise ValueError("World " + field + " keys must be non-empty strings")
    if not isinstance(data["events"], list):
        raise ValueError("World events must be a list")
    if not data["locations"] or not data["actors"]:
        raise ValueError("World needs locations and actors")
    for key, location in data["locations"].items():
        _named_record(location, {"id", "name", "description", "connections"}, "location " + key)
        if location["id"] != key:
            raise ValueError("Invalid location " + key)
        _strings(location, ("id", "name", "description"), "location " + key)
        _string_list(location["connections"], "location connections")
        if any(item not in data["locations"] for item in location["connections"]):
            raise ValueError("Unknown location connection in " + key)
    for key, item in data["items"].items():
        _named_record(item, {"id", "name", "description"}, "item " + key)
        if item["id"] != key:
            raise ValueError("Item id does not match " + key)
        _strings(item, ("id", "name", "description"), "item " + key)
    for key, fact in data["facts"].items():
        _named_record(fact, {"id", "text", "secret", "required_trust", "required_quest"}, "fact " + key)
        if fact["id"] != key or type(fact["secret"]) is not bool:
            raise ValueError("Invalid fact " + key)
        _strings(fact, ("id", "text"), "fact " + key)
        if type(fact["required_trust"]) is not int or fact["required_trust"] < 0:
            raise ValueError("Invalid fact trust threshold " + key)
        if fact["required_quest"] is not None and (not isinstance(fact["required_quest"], str) or fact["required_quest"] not in data["quests"]):
            raise ValueError("Unknown quest for fact " + key)
    if any(type(value) is not bool for value in data["quests"].values()):
        raise ValueError("Quest values must be boolean")
    owned = []
    actor_fields = {"id", "name", "role", "persona", "goal", "location", "inventory", "trust", "belief", "allowed_actions", "memories"}
    for key, actor in data["actors"].items():
        _record(actor, actor_fields, "actor " + key)
        _strings(actor, ("id", "name", "role", "persona", "goal", "location"), "actor " + key)
        if actor["id"] != key or actor["location"] not in data["locations"]:
            raise ValueError("Invalid actor id/location " + key)
        for field in ("name", "role", "persona", "goal"):
            if not isinstance(actor[field], str):
                raise ValueError("Invalid actor " + field + " " + key)
        for field in ("inventory", "allowed_actions", "memories"):
            if not isinstance(actor[field], list):
                raise ValueError("Actor " + field + " must be a list")
        _string_list(actor["inventory"], "actor inventory")
        _string_list(actor["allowed_actions"], "allowed actions")
        if any(item not in data["items"] for item in actor["inventory"]):
            raise ValueError("Unknown inventory item " + key)
        if any(action not in {"speak", "move", "give"} for action in actor["allowed_actions"]):
            raise ValueError("Unknown allowed action " + key)
        owned.extend(actor["inventory"])
        _record(actor["belief"], {"known_facts"}, "belief " + key)
        known = actor["belief"]["known_facts"]
        _string_list(known, "known facts")
        if any(fact not in data["facts"] for fact in known):
            raise ValueError("Unknown belief fact " + key)
        if not isinstance(actor["trust"], dict) or any(
            target not in data["actors"] or type(score) is not int or score < 0
            for target, score in actor["trust"].items()
        ):
            raise ValueError("Invalid actor trust " + key)
    if len(owned) != len(set(owned)):
        raise ValueError("Each item may have only one owner")
    from .rules import validate_rules

    validate_rules(data)
    _validate_history(data)


def _record(value: Any, keys: set, label: str) -> None:
    if not isinstance(value, dict) or set(value) != keys:
        raise ValueError("Invalid fields for " + label)


def _named_record(value: Any, keys: set, label: str) -> None:
    """Validate optional command aliases without accepting arbitrary metadata."""
    if not isinstance(value, dict) or not keys <= set(value) <= keys | {"aliases"}:
        raise ValueError("Invalid fields for " + label)
    if "aliases" in value:
        _string_list(value["aliases"], label + " aliases")
        if any(not alias.strip() for alias in value["aliases"]):
            raise ValueError("Empty command alias in " + label)


def _strings(value: dict, keys: tuple, label: str) -> None:
    if any(not isinstance(value[key], str) or not value[key] for key in keys):
        raise ValueError("Expected non-empty strings for " + label)


def _string_list(value: Any, label: str) -> None:
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise ValueError("Expected string list for " + label)
    if len(value) != len(set(value)):
        raise ValueError("Duplicate entries in " + label)


def _validate_history(data: dict) -> None:
    from .parser import parse_action

    events = {}
    event_fields = {"id", "tick", "type", "actor_id", "location", "participants", "witnesses", "summary", "action"}
    for index, event in enumerate(data["events"], 1):
        _record(event, event_fields, "event")
        _strings(event, ("id", "type", "actor_id", "location", "summary"), "event")
        _string_list(event["participants"], "event participants")
        _string_list(event["witnesses"], "event witnesses")
        if type(event["tick"]) is not int or event["tick"] != index or event["id"] in events:
            raise ValueError("Invalid event tick/id sequence")
        if event["actor_id"] not in data["actors"] or event["location"] not in data["locations"]:
            raise ValueError("Unknown actor/location in event")
        if any(key not in data["actors"] for key in event["participants"] + event["witnesses"]):
            raise ValueError("Unknown event participant/witness")
        if not set(event["participants"]) <= set(event["witnesses"]):
            raise ValueError("Event participants must witness their action")
        action = parse_action(event["action"])
        if action.type != event["type"] or action.actor_id != event["actor_id"]:
            raise ValueError("Event action does not match its actor/type")
        events[event["id"]] = event
    if data["tick"] != len(data["events"]):
        raise ValueError("World tick must match the complete event history")
    memory_fields = {"id", "event_id", "tick", "summary", "actor_ids", "location", "importance"}
    for actor_id, actor in data["actors"].items():
        memory_ids = set()
        for memory in actor["memories"]:
            _record(memory, memory_fields, "memory")
            _strings(memory, ("id", "event_id", "summary", "location"), "memory")
            _string_list(memory["actor_ids"], "memory actors")
            if memory["id"] in memory_ids or memory["event_id"] not in events:
                raise ValueError("Duplicate memory id or missing source event")
            source = events[memory["event_id"]]
            if actor_id not in source["witnesses"]:
                raise ValueError("Memory owner did not witness its source event")
            if type(memory["tick"]) is not int or memory["tick"] != source["tick"]:
                raise ValueError("Memory tick must match its source event")
            if memory["summary"] != source["summary"] or memory["actor_ids"] != source["participants"] or memory["location"] != source["location"]:
                raise ValueError("Memory provenance does not match its source event")
            if type(memory["importance"]) is not int or memory["importance"] < 0:
                raise ValueError("Memory importance must be a non-negative integer")
            memory_ids.add(memory["id"])


def read_data(name: str) -> Any:
    """Read bundled JSON data even when installed from a wheel."""
    return json.loads(resources.files("loom_npc").joinpath("data", name).read_text(encoding="utf-8"))


def load_world(path: Optional[Union[str, Path]] = None) -> WorldState:
    """Load a validated world; the default is the bundled Lantern Town."""
    data = read_data("lantern_town.json") if path is None else json.loads(Path(path).read_text(encoding="utf-8"))
    return WorldState(data)
